### ISSUE TITLE
[Tracking] Roadmap Q3 2019

### ISSUE THREAD

**Issue by Rover656** [NerdThings/Ngine#13]
# 2019 Q3 Tracker
This is a tracker to allow me to see what needs to be done this quarter.

UPDATE: As we are proceeding with #15, many of these will be completed there, and the timescale has been pushed back. Closed as a result

## Todo's
- [ ] Fix memory leaks.
- [ ] Improved resource loading, additionally allow directories to be marked by type instead of per-extension. Will be done in #15.
- [ ] Tileset collisions (properly).
- [ ] Type register, keeping track of all entity types, scene types etc. Dumb idea, not being done
- [ ] Built in tiled support (with the ability for objects to represent entities).
- [ ] Redo UI engine using canvases.
- [ ] Scene wide saving and loading.
